# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-18 18:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='name',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='trip',
            name='notes',
            field=models.CharField(blank=True, max_length=400),
        ),
    ]
