# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-09 00:04
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Profile', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='document',
            name='document_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Profile.DocumentType'),
        ),
        migrations.AddField(
            model_name='document',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Profile.Profile'),
        ),
        migrations.AddField(
            model_name='clientsofagents',
            name='agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Profile.Agent'),
        ),
        migrations.AddField(
            model_name='clientsofagents',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clients', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='agent',
            name='agent_profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Profile.Profile'),
        ),
        migrations.AddField(
            model_name='agent',
            name='brokerage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Profile.Brokerage'),
        ),
        migrations.AddField(
            model_name='agent',
            name='clients',
            field=models.ManyToManyField(blank=True, through='Profile.ClientsOfAgents', to=settings.AUTH_USER_MODEL),
        ),
    ]
