# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-09 01:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0002_auto_20170608_2004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='brokerage',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Profile.Brokerage'),
        ),
    ]
